#!/usr/bin/env bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../../Manual-Non-Aspire-Local-Dev/Infrastructure/Terraform-Dev"
API_DIR="$SCRIPT_DIR/../../Manual-Non-Aspire-Local-Dev/Services/API/Todo.API"
REACT_DIR="$SCRIPT_DIR/../../Manual-Non-Aspire-Local-Dev/Services/Web/React/todo"
ANGULAR_DIR="$SCRIPT_DIR/../../Manual-Non-Aspire-Local-Dev/Services/Web/Angular/todo"

echo -e "${CYAN}========================================"
echo -e "Todo App - Development Environment Setup"
echo -e "========================================${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}ERROR: Terraform is not installed or not in PATH${NC}"
    echo -e "${RED}Install from: https://www.terraform.io/downloads${NC}"
    exit 1
fi

if ! command -v az &> /dev/null; then
    echo -e "${RED}ERROR: Azure CLI is not installed or not in PATH${NC}"
    echo -e "${RED}Install from: https://docs.microsoft.com/cli/azure/install-azure-cli${NC}"
    exit 1
fi

if ! az account show &> /dev/null; then
    echo -e "${RED}ERROR: Not logged into Azure CLI${NC}"
    echo -e "${YELLOW}Run: az login${NC}"
    exit 1
fi

TERRAFORM_VERSION=$(terraform version -json | jq -r '.terraform_version')
AZURE_USER=$(az account show --query user.name -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)

echo -e "${GREEN}✓ Terraform installed: $TERRAFORM_VERSION${NC}"
echo -e "${GREEN}✓ Azure CLI logged in as: $AZURE_USER${NC}"
echo -e "${GREEN}✓ Tenant: $TENANT_ID${NC}"
echo ""

# Create terraform.tfvars if it doesn't exist
TFVARS_PATH="$TERRAFORM_DIR/terraform.tfvars"
if [ ! -f "$TFVARS_PATH" ]; then
    echo -e "${YELLOW}Creating terraform.tfvars...${NC}"
    echo "tenant_id = \"$TENANT_ID\"" > "$TFVARS_PATH"
    echo -e "${GREEN}✓ Created terraform.tfvars with tenant ID: $TENANT_ID${NC}"
    echo ""
fi

# Initialize and apply Terraform
echo -e "${YELLOW}Initializing Terraform...${NC}"
cd "$TERRAFORM_DIR"
terraform init

echo -e "${GREEN}✓ Terraform initialized${NC}"
echo ""

echo -e "${YELLOW}Creating Azure AD app registrations...${NC}"
echo -e "${CYAN}(This will create: todo-api-dev, todo-react-dev, todo-angular-dev)${NC}"
echo ""

terraform apply -auto-approve

echo ""
echo -e "${GREEN}✓ App registrations created successfully${NC}"
echo ""

# Get Terraform outputs
echo -e "${YELLOW}Retrieving configuration values...${NC}"
API_CLIENT_ID=$(terraform output -raw api_client_id)
REACT_CLIENT_ID=$(terraform output -raw react_client_id)
ANGULAR_CLIENT_ID=$(terraform output -raw angular_client_id)
API_SCOPE=$(terraform output -raw api_scope)
API_AUDIENCE=$(terraform output -raw api_audience)

cd - > /dev/null

echo ""
echo -e "${CYAN}========================================"
echo -e "Generating environment configuration files"
echo -e "========================================${NC}"
echo ""

# Generate API appsettings.Development.json
API_SETTINGS_PATH="$API_DIR/appsettings.Development.json"
if [ -f "$API_SETTINGS_PATH" ] && [ "$1" != "--force" ]; then
    echo -e "${YELLOW}⚠ $API_SETTINGS_PATH already exists (use --force to overwrite)${NC}"
else
    cat > "$API_SETTINGS_PATH" << EOF
{
  "RunWithAuth": true,
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "$TENANT_ID",
    "ClientId": "$API_CLIENT_ID",
    "Audience": "$API_AUDIENCE"
  }
}
EOF
    echo -e "${GREEN}✓ Created $API_SETTINGS_PATH${NC}"
fi

# Generate React .env
REACT_ENV_PATH="$REACT_DIR/.env"
if [ -f "$REACT_ENV_PATH" ] && [ "$1" != "--force" ]; then
    echo -e "${YELLOW}⚠ $REACT_ENV_PATH already exists (use --force to overwrite)${NC}"
else
    cat > "$REACT_ENV_PATH" << EOF
# Vite environment variables for local development
# Auto-generated by setup-dev-environment.sh

# Set to "true" to bypass auth in development (convenience only)
VITE_BYPASS_AUTH_IN_DEV=false

# Azure Entra ID / Microsoft Identity values
VITE_CLIENT_ID=$REACT_CLIENT_ID
VITE_TENANT_ID=$TENANT_ID
VITE_REDIRECT_URI=https://localhost:5173
VITE_POST_LOGOUT_REDIRECT_URI=https://localhost:5173

# API settings (use /api for development proxy)
VITE_API_BASE_URL=/api

# Scopes as a JSON array string
VITE_API_SCOPES=["$API_SCOPE"]
EOF
    echo -e "${GREEN}✓ Created $REACT_ENV_PATH${NC}"
fi

# Generate Angular .env
ANGULAR_ENV_PATH="$ANGULAR_DIR/.env"
if [ -f "$ANGULAR_ENV_PATH" ] && [ "$1" != "--force" ]; then
    echo -e "${YELLOW}⚠ $ANGULAR_ENV_PATH already exists (use --force to overwrite)${NC}"
else
    cat > "$ANGULAR_ENV_PATH" << EOF
# Angular environment variables for local development
# Auto-generated by setup-dev-environment.sh

NG_APP_bypassAuthInDev=false
NG_APP_production=false

# Azure Entra ID / Microsoft Identity values
NG_APP_AzureAd__ClientID=$ANGULAR_CLIENT_ID
NG_APP_AzureAd__TenantId=$TENANT_ID
NG_APP_AzureAd__Instance=https://login.microsoftonline.com/
NG_APP_RedirectUri=https://localhost:4200
NG_APP_PostLogoutRedirectUri=https://localhost:4200

# API settings (use /api for development proxy)
NG_APP_apiBaseUrl=https://localhost:4200/api/*
NG_APP_API_BASE_URL=/api

# API Scopes
NG_APP_AzureAd__Audience=$API_AUDIENCE
NG_APP_AzureAd__Scopes=access_as_user
NG_APP_apiScopes=$API_SCOPE
EOF
    echo -e "${GREEN}✓ Created $ANGULAR_ENV_PATH${NC}"
fi

echo ""
echo -e "${GREEN}========================================"
echo -e "✓ Development environment setup complete!"
echo -e "========================================${NC}"
echo ""
echo -e "${CYAN}App Registration Details:${NC}"
echo -e "  API Client ID:     $API_CLIENT_ID"
echo -e "  React Client ID:   $REACT_CLIENT_ID"
echo -e "  Angular Client ID: $ANGULAR_CLIENT_ID"
echo -e "  Tenant ID:         $TENANT_ID"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo -e "  1. Start the API:     cd Services/API/Todo.API && dotnet run"
echo -e "  2. Start React:       cd Services/Web/React/todo && npm run dev"
echo -e "  3. Start Angular:     cd Services/Web/Angular/todo && npm start"
echo ""
echo -e "${YELLOW}Note: You may need to grant admin consent for API permissions:"
echo -e "  Azure Portal > Entra ID > App Registrations > todo-react-dev/todo-angular-dev > API permissions > Grant admin consent${NC}"
echo ""
